[en]
    contentDir = 'content/en'
    disabled = false
    languageCode = 'en-GB'
    languageDirection = 'ltr'
    languageName = 'English'
    [en.pagination]
        disableAliases = false
        pagerSize = 6
        path = 'page'

[zh]
    contentDir = 'content/zh'
    disabled = false
    languageCode = 'zh-CN'
    languageDirection = 'ltr'
    languageName = 'Chinese'
    [zh.pagination]
        disableAliases = false
        pagerSize = 6
        path = 'page'