[[main]]
  name       = 'Github'
  identifier = 'github'
  weight     = 3
  url        = 'https://github.com/mukimasta'
  pre        = 'github'
  [[main.params]]
    target   = '_blank'

[[main]]
  name       = 'About'
  identifier = 'about'
  pageRef    = '/'
  weight     = 1



# [[footer]]
#   identifier = 'figma'
#   pageRef    = '/'
#   weight     = 1
#   name       = 'figma'
#   pre        = 'figma'

# [[footer]]
#   identifier = 'hashnode'
#   pageRef    = '/'
#   weight     = 2
#   name       = 'hashnode'
#   pre        = 'hashnode'

# [[footer]]
#   identifier = 'email'
#   pageRef    = '/'
#   weight     = 3
#   name       = 'email'
#   pre        = 'email'

# [[footer]]
#   identifier = 'linkedin'
#   pageRef    = '/'
#   weight     = 4
#   name       = 'linkedin'
#   pre        = 'linkedin'

# [[footer]]
#   identifier = 'karyakarsa'
#   pageRef    = '/'
#   weight     = 5
#   name       = 'karya karsa'
#   pre        = 'karyakarsa'

# [[contrib]]
#   identifier = 'githubsponsors'
#   url        = 'https://github.com/sponsors/foxihd/'
#   name       = 'Become Github Sponsors'
#   pre        = 'githubsponsors'